'use strict';

module.exports = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EXPRESSION: 'INVALID_EXPRESSION',
  EVAL_FAILED: 'EVAL_FAILED',
  UNKNOWN_METHOD: 'UNKNOWN_METHOD',
  SOLVER_PRECONDITION_FAILED: 'SOLVER_PRECONDITION_FAILED',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  REPORT_GENERATION_ERROR: 'REPORT_GENERATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
